# Generated by Django 4.2.7 on 2023-12-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('nomor', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
    ]
